name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1
            TERRAFORM_TELEMETRY: 0
            VCPKG_DISABLE_METRICS: 1

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.2.2

            - uses: actions/setup-node@v4.1.0
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./crates/oxc_traverse/scripts
              continue-on-error: true
              working-directory: ./crates/oxc_traverse/scripts
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_wasm
              continue-on-error: true
              working-directory: ./crates/oxc_wasm
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./editors/vscode
              continue-on-error: true
              working-directory: ./editors/vscode
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./napi/minify
              continue-on-error: true
              working-directory: ./napi/minify
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./napi/parser
              continue-on-error: true
              working-directory: ./napi/parser
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./napi/transform
              continue-on-error: true
              working-directory: ./napi/transform
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc-parser
              continue-on-error: true
              working-directory: ./npm/oxc-parser
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc-transform
              continue-on-error: true
              working-directory: ./npm/oxc-transform
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc-types
              continue-on-error: true
              working-directory: ./npm/oxc-types
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc
              continue-on-error: true
              working-directory: ./npm/oxc
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxlint
              continue-on-error: true
              working-directory: ./npm/oxlint
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/parser-wasm
              continue-on-error: true
              working-directory: ./npm/parser-wasm
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish .
              continue-on-error: true
              working-directory: .
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/benchmark/codspeed
              continue-on-error: true
              working-directory: ./tasks/benchmark/codspeed
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/compat_data
              continue-on-error: true
              working-directory: ./tasks/compat_data
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/coverage/Source/runtime
              continue-on-error: true
              working-directory: ./tasks/coverage/Source/runtime
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/lint_rules
              continue-on-error: true
              working-directory: ./tasks/lint_rules
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/transform_conformance
              continue-on-error: true
              working-directory: ./tasks/transform_conformance
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm/parser
              continue-on-error: true
              working-directory: ./wasm/parser
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./website
              continue-on-error: true
              working-directory: ./website
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
