name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.5

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./editors/vscode
              continue-on-error: true
              working-directory: ./editors/vscode
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./napi/parser
              continue-on-error: true
              working-directory: ./napi/parser
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc-parser
              continue-on-error: true
              working-directory: ./npm/oxc-parser
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc
              continue-on-error: true
              working-directory: ./npm/oxc
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxlint
              continue-on-error: true
              working-directory: ./npm/oxlint
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/benchmark/codspeed
              continue-on-error: true
              working-directory: ./tasks/benchmark/codspeed
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/coverage/Source/runtime
              continue-on-error: true
              working-directory: ./tasks/coverage/Source/runtime
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/lint_rules
              continue-on-error: true
              working-directory: ./tasks/lint_rules
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm/parser
              continue-on-error: true
              working-directory: ./wasm/parser
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./website
              continue-on-error: true
              working-directory: ./website
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
