name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.2

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./crates/oxc_linter/fixtures/import/bundled-dependencies/as-array-bundle-deps
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/bundled-dependencies/as-array-bundle-deps
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/bundled-dependencies/as-object
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/bundled-dependencies/as-object
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/bundled-dependencies/race-condition
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/bundled-dependencies/race-condition
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/empty
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/empty
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/internal-modules
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/internal-modules
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/missing-entrypoint
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/missing-entrypoint
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/monorepo
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/monorepo
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/monorepo/packages/nested-package
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/monorepo/packages/nested-package
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/no-unused-modules/binObject
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/no-unused-modules/binObject
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/no-unused-modules/browserObject
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/no-unused-modules/browserObject
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/no-unused-modules
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/no-unused-modules
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/no-unused-modules/privatePkg
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/no-unused-modules/privatePkg
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/order-redirect-scoped/module
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/order-redirect-scoped/module
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/order-redirect-scoped
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/order-redirect-scoped
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/order-redirect/module
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/order-redirect/module
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/order-redirect
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/order-redirect
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/package-named
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/package-named
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/package-scoped
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/package-scoped
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/package
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/package
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/symlinked-module
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/symlinked-module
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/with-flow-typed
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/with-flow-typed
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./crates/oxc_linter/fixtures/import/with-typescript-dev-dependencies
              continue-on-error: true
              working-directory: ./crates/oxc_linter/fixtures/import/with-typescript-dev-dependencies
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./editors/vscode
              continue-on-error: true
              working-directory: ./editors/vscode
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./napi/parser
              continue-on-error: true
              working-directory: ./napi/parser
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc-parser
              continue-on-error: true
              working-directory: ./npm/oxc-parser
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxc
              continue-on-error: true
              working-directory: ./npm/oxc
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./npm/oxlint
              continue-on-error: true
              working-directory: ./npm/oxlint
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/benchmark/codspeed
              continue-on-error: true
              working-directory: ./tasks/benchmark/codspeed
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/coverage/Source/runtime
              continue-on-error: true
              working-directory: ./tasks/coverage/Source/runtime
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./tasks/lint_rules
              continue-on-error: true
              working-directory: ./tasks/lint_rules
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm/parser
              continue-on-error: true
              working-directory: ./wasm/parser
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./website
              continue-on-error: true
              working-directory: ./website
              run: |
                  npm install --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
